# Generated by Django 2.2.5 on 2019-12-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'чат', 'verbose_name_plural': 'чаты'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(default=False, verbose_name='признак группового чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(default=None, null=True, verbose_name='последнее сообщение'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='topic',
            field=models.CharField(max_length=32, verbose_name='тема/название чата'),
        ),
    ]
