# Generated by Django 2.2.5 on 2019-12-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20191201_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='topic',
            field=models.CharField(max_length=255, verbose_name='тема/название чата'),
        ),
    ]
