# Generated by Django 2.2.5 on 2019-12-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191127_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(default='', max_length=16, verbose_name='ник пользователя'),
        ),
    ]
