# Generated by Django 2.2.5 on 2019-12-01 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20191201_2058'),
        ('members', '0003_auto_20191127_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'участник', 'verbose_name_plural': 'участники'},
        ),
        migrations.AlterField(
            model_name='member',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Chat', verbose_name='чат, в котором состоит участник'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_read_message',
        ),
        migrations.AddField(
            model_name='member',
            name='last_read_message',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='message.Message', verbose_name='последнее прочитанное сообщение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='new_messages',
            field=models.IntegerField(default=0, verbose_name='количество непрочитанных сообщений'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='участник чата'),
        ),
    ]
