# Generated by Django 2.2.5 on 2019-12-01 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_auto_20191127_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'приложенный файл', 'verbose_name_plural': 'приложенные файлы'},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='type',
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachmentType',
            field=models.CharField(default='документ', max_length=16, verbose_name='тип приложенного файла'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Chat', verbose_name='чат, в котором приложенный файл'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Message', verbose_name='сообщение, к которому приложен файл'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.TextField(verbose_name='ссылка на приложенный файл'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь, который приложил файл'),
        ),
    ]
