# Generated by Django 2.2.5 on 2019-12-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_auto_20191201_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='attachmentType',
            new_name='attachment_type',
        ),
    ]
