# Generated by Django 2.2.5 on 2019-12-01 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20191127_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-added_at'], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(auto_now=True, verbose_name='время отправки сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Chat', verbose_name='чат, в котором содержится сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='', verbose_name='текст сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь, который отправил сообщение'),
        ),
    ]
